version: "3.8"

services:
  #
  # For local development use memory volumes
  #
  shard1:
    image: apache/kvrocks:nightly-20231118-358cc41
    container_name: mosaic-shard1
    restart: always
    ports:
      - "0.0.0.0:6751:6666"
    networks:
      - localnetwork

  shard2:
    image: apache/kvrocks:nightly-20231118-358cc41
    container_name: mosaic-shard2
    restart: always
    ports:
      - "0.0.0.0:6752:6666"
    networks:
      - localnetwork

  shard3:
    image: apache/kvrocks:nightly-20231118-358cc41
    container_name: mosaic-shard3
    restart: always
    ports:
      - "0.0.0.0:6753:6666"
    networks:
      - localnetwork

  shard4:
    image: apache/kvrocks:nightly-20231118-358cc41
    container_name: mosaic-shard4
    restart: always
    ports:
      - "0.0.0.0:6754:6666"
    networks:
      - localnetwork

  shard5:
    image: apache/kvrocks:nightly-20231118-358cc41
    container_name: mosaic-shard5
    restart: always
    ports:
      - "0.0.0.0:6755:6666"
    networks:
      - localnetwork

  shard6:
    image: apache/kvrocks:nightly-20231118-358cc41
    container_name: mosaic-shard6
    restart: always
    ports:
      - "0.0.0.0:6756:6666"
    networks:
      - localnetwork

  shard7:
    image: apache/kvrocks:nightly-20231118-358cc41
    container_name: mosaic-shard7
    restart: always
    ports:
      - "0.0.0.0:6757:6666"
    networks:
      - localnetwork

  shard8:
    image: apache/kvrocks:nightly-20231118-358cc41
    container_name: mosaic-shard8
    restart: always
    ports:
      - "0.0.0.0:6758:6666"
    networks:
      - localnetwork

  shard9:
    image: apache/kvrocks:nightly-20231118-358cc41
    container_name: mosaic-shard9
    restart: always
    ports:
      - "0.0.0.0:6759:6666"
    networks:
      - localnetwork

  shard10:
    image: apache/kvrocks:nightly-20231118-358cc41
    container_name: mosaic-shard10
    restart: always
    ports:
      - "0.0.0.0:6760:6666"
    networks:
      - localnetwork

networks:
  localnetwork:
    driver: bridge